// Explicit translations; no DOM text replacement or recursive mutation observers.
const strings = {
  quickView:['Быстрый просмотр','Жылдам қарау','Quick view'],
  openProfile:['Открыть профиль региона','Өңір профилін ашу','Open region profile'],
  backToRegions:['К списку регионов','Өңірлер тізіміне','Back to regions'],
  analysisOverview:['Обзор','Шолу','Overview'],
  compact:['Компактно','Ықшам','Compact'],
  yearToDate:['с начала года','жыл басынан','year to date'],
  brand:['Атлас антимикробной резистентности','Микробқа қарсы тұрақтылық атласы','Antimicrobial resistance atlas'],
  mapNav:['Карта и регионы','Карта және өңірлер','Map & regions'],
  reference:['Справочник','Анықтамалық','Reference'],
  mechanisms:['Механизмы AMR','AMR механизмдері','AMR mechanisms'],
  methodology:['Данные и методология','Деректер және әдіснама','Data & methodology'],
  demo:['Демонстрационный прототип','Демонстрациялық прототип','Demonstration prototype'],
  notice:['Все показатели синтетические. Они показывают возможности платформы, а не эпидемиологическую ситуацию в Казахстане.','Барлық көрсеткіштер синтетикалық. Олар Қазақстандағы эпидемиологиялық жағдайды емес, платформаның мүмкіндіктерін көрсетеді.','All values are synthetic. They demonstrate the platform, not the epidemiological situation in Kazakhstan.'],
  learn:['О данных','Деректер туралы','About the data'],
  eyebrow:['МОНИТОРИНГ AMR · КАЗАХСТАН','AMR МОНИТОРИНГІ · ҚАЗАҚСТАН','AMR SURVEILLANCE · KAZAKHSTAN'],
  countryTitle:['Карта резистентности Казахстана','Қазақстанның тұрақтылық картасы','Resistance across Kazakhstan'],
  countrySubtitle:['От национального обзора — к подробной картине каждого региона.','Ұлттық шолудан әр өңірдің толық көрінісіне.','From a national overview to a detailed picture of every region.'],
  regional:['РЕГИОНАЛЬНЫЙ ПРОФИЛЬ','ӨҢІРЛІК ПРОФИЛЬ','REGIONAL PROFILE'],
  regionSubtitle:['Карта территории и все доступные показатели выбранного среза.','Аумақ картасы және таңдалған деректердің барлық қолжетімді көрсеткіштері.','Territory map and all available metrics for the selected cohort.'],
  export:['Скачать CSV','CSV жүктеп алу','Download CSV'],
  home:['На главную карту','Басты картаға','Back to national map'],
  organism:['Микроорганизм','Микроорганизм','Organism'],
  drug:['Антибиотик','Антибиотик','Antimicrobial'],
  material:['Материал','Материал','Specimen'],
  period:['Период','Кезең','Period'],
  territory:['Территория','Аумақ','Territory'],
  allRegions:['Весь Казахстан','Бүкіл Қазақстан','All Kazakhstan'],
  tested:['Протестировано','Сыналған изоляттар','Tested isolates'],
  testedNote:['изолятов для выбранной пары','таңдалған жұп үшін изолят','isolates for the selected pair'],
  resistance:['Доля резистентных','Тұрақты изоляттардың үлесі','Resistant isolates'],
  ci:['95% ДИ','95% СА','95% CI'],
  laboratories:['Лаборатории модели','Модель зертханалары','Model laboratories'],
  labsNote:['условные участники, не реальный охват','шартты қатысушылар, нақты қамту емес','fictional contributors, not real coverage'],
  territories:['Территории модели','Модель аумақтары','Model territories'],
  territoryNote:['17 областей и 3 города','17 облыс және 3 қала','17 regions and 3 cities'],
  testedDrugs:['Препаратов в профиле','Профильдегі препараттар','Antimicrobials in profile'],
  noPooling:['каждая пара имеет свой знаменатель N','әр жұптың жеке N бөлімі бар','each pair has its own denominator N'],
  mapTitle:['География резистентности','Тұрақтылық географиясы','The geography of resistance'],
  mapHint:['Выберите область на карте или в списке','Картадан немесе тізімнен облысты таңдаңыз','Select a territory on the map or in the list'],
  regionMap:['Карта территории','Аумақ картасы','Territory map'],
  mapRegionHint:['Города, населённые пункты и дороги выбранного региона','Таңдалған өңірдің қалалары, елді мекендері және жолдары','Cities, settlements and roads in the selected region'],
  geoMapHint:['Перетаскивайте карту и меняйте масштаб. Географическая подложка не содержит AMR-статистику.','Картаны жылжытып, масштабты өзгертіңіз. Географиялық қабатта AMR статистикасы жоқ.','Drag the map and change zoom. The geographic basemap does not contain AMR statistics.'],
  geoMapSource:['Географическая подложка','Географиялық негіз','Geographic basemap'],
  north:['С','С','N'],
  scale:['Доля R, %','R үлесі, %','R proportion, %'],
  noData:['Недостаточно данных','Деректер жеткіліксіз','Insufficient data'],
  neutralScale:['Цвет показывает долю R, а не оценку качества региона.','Түс өңір сапасын емес, R үлесін көрсетеді.','Colour shows the R proportion, not a rating of the region.'],
  mapSource:['Локальные контуры · версия 2024 · справочная карта','Жергілікті шекаралар · 2024 нұсқасы · анықтамалық карта','Local boundaries · 2024 version · reference map'],
  regions:['Регионы','Өңірлер','Territories'],
  search:['Найти регион…','Өңірді іздеу…','Find a territory…'],
  alphabetical:['По алфавиту · выберите для просмотра','Әліпби бойынша · көру үшін таңдаңыз','Alphabetical · select to explore'],
  emptySearch:['Регион не найден. Измените запрос.','Өңір табылмады. Сұрауды өзгертіңіз.','No territory found. Try another search.'],
  distribution:['Распределение S / I / R','S / I / R үлестірімі','S / I / R distribution'],
  distributionNote:['Одна пара, один материал, один период','Бір жұп, бір материал, бір кезең','One pair, one specimen, one period'],
  s:['S · Чувствительные','S · Сезімтал','S · Susceptible'],
  i:['I · Чувствительные при увеличенной экспозиции','I · Жоғары экспозицияда сезімтал','I · Susceptible, increased exposure'],
  r:['R · Резистентные','R · Тұрақты','R · Resistant'],
  euNote:['Терминология EUCAST. Категория I не объединяется с R.','EUCAST терминологиясы. I санаты R санатына қосылмайды.','EUCAST terminology. I is not combined with R.'],
  countryBaseline:['В сравнении с Казахстаном','Қазақстанмен салыстыру','Compared with Kazakhstan'],
  sameCohort:['та же пара, материал и период','сол жұп, материал және кезең','same pair, specimen and period'],
  pp:['п.п.','п.т.','pp'],
  below:['ниже доли по модели страны','ел моделінің үлесінен төмен','below the model national proportion'],
  above:['выше доли по модели страны','ел моделінің үлесінен жоғары','above the model national proportion'],
  equal:['на уровне модели страны','ел моделі деңгейінде','equal to the model national proportion'],
  noRanking:['Различие долей не доказывает различие качества помощи.','Үлестердің айырмасы медициналық көмек сапасының айырмасын дәлелдемейді.','A difference in proportions does not establish a difference in care quality.'],
  overview:['Подробная статистика','Толық статистика','Detailed statistics'],
  antibiotics:['Профиль по антибиотикам','Антибиотиктер профилі','Antimicrobial profile'],
  antibioticsNote:['Отдельный знаменатель для каждого препарата','Әр препарат үшін жеке бөлім','Separate denominator for each antimicrobial'],
  trend:['Динамика по годам','Жылдар бойынша динамика','Yearly trend'],
  trendNote:['Одинаковые фильтры; последний период может быть неполным.','Сүзгілер бірдей; соңғы кезең толық болмауы мүмкін.','Same filters; the latest period may be incomplete.'],
  trendWarning:['2026: 01.01–20.09. Не сравнивайте неполный год с полным без поправки на состав выборки.','2026: 01.01–20.09. Іріктеме құрамын ескермей толық емес жылды толық жылмен салыстырмаңыз.','2026: Jan 1–Sep 20. Do not directly compare a partial year with a full year without accounting for cohort composition.'],
  allSpecimens:['Структура по материалам','Материалдар құрылымы','Specimen breakdown'],
  allSpecimensNote:['Все материалы для выбранной пары и периода. Строки не зависят от фильтра материала.','Таңдалған жұп пен кезеңнің барлық материалдары. Жолдар материал сүзгісіне тәуелді емес.','All specimens for the selected pair and period. Rows are independent of the specimen filter.'],
  sample:['Выборка','Іріктеме','Sample'],
  year:['Год','Жыл','Year'],
  suppressed:['Скрыто: N < 30','Жасырылған: N < 30','Suppressed: N < 30'],
  unavailable:['Нет данных','Деректер жоқ','No data'],
  precision:['При N < 30 доли, числители и доверительные интервалы не публикуются. Это правило проекта для малых выборок, не установленный законом порог.','N < 30 болса, үлестер, алымдар және сенім аралықтары жарияланбайды. Бұл заң талабы емес, шағын іріктемелерге арналған жоба ережесі.','For N < 30, proportions, numerators and confidence intervals are withheld. This is a project rule for small samples, not a statutory threshold.'],
  passport:['Паспорт данных','Деректер паспорты','Data provenance'],
  source:['Источник','Дереккөз','Source'],
  sourceValue:['Синтетическая модель · клинических наблюдений нет','Синтетикалық модель · клиникалық бақылаулар жоқ','Synthetic model · no clinical observations'],
  indicator:['Расчёт','Есептеу','Calculation'],
  indicatorValue:['R / (S + I + R) × 100%; N = S + I + R','R / (S + I + R) × 100%; N = S + I + R','R / (S + I + R) × 100%; N = S + I + R'],
  version:['Версия модели','Модель нұсқасы','Model version'],
  dedup:['Дедупликация / критерии AST','Қайталанулар / AST критерийлері','Deduplication / AST breakpoints'],
  dedupValue:['Не применяются к синтетическим агрегатам. Для реального источника нужны версии правил и стандарта.','Синтетикалық агрегаттарға қолданылмайды. Нақты дереккөз үшін ережелер мен стандарт нұсқалары қажет.','Not applied to synthetic aggregates. Real sources require versioned rules and a declared standard.'],
  confidence:['Доверительный интервал','Сенім аралығы','Confidence interval'],
  confidenceValue:['Метод Уилсона, 95%','Уилсон әдісі, 95%','Wilson method, 95%'],
  quality:['Доступность данных','Деректердің қолжетімділігі','Data availability'],
  qualityValue:['Реальные наблюдения, районы, учреждения и подтверждённые механизмы пока не подключены. Они не заменяются вымышленной статистикой в этом профиле.','Нақты бақылаулар, аудандар, ұйымдар және расталған механизмдер әзірге қосылмаған. Бұл профильде олар ойдан шығарылған статистикамен алмастырылмайды.','Real observations, districts, facilities and confirmed mechanisms are not connected. This profile does not invent statistics for them.'],
  legal:['Конфиденциальность и правовая основа','Құпиялық және құқықтық негіз','Privacy & legal basis'],
  lawTitle:['Правила публичного прототипа','Ашық прототип ережелері','Public prototype rules'],
  publicRule:['Эта витрина показывает только синтетические агрегаты. Здесь нет загрузки историй пациентов, ИИН, ФИО, дат рождения или первичных результатов. CSV содержит только показатели текущего представления.','Бұл витрина тек синтетикалық агрегаттарды көрсетеді. Мұнда пациент тарихын, ЖСН, аты-жөнін, туған күнін немесе бастапқы нәтижелерді жүктеу жоқ. CSV тек ағымдағы көрініс көрсеткіштерін қамтиды.','This explorer shows synthetic aggregates only. It has no upload of patient histories, identifiers, names, dates of birth or individual results. CSV exports contain only the current aggregate view.'],
  lawPersonal:['Персональные данные: основание обработки, минимизация, хранение в Казахстане и обезличивание для исследований — статьи 7, 12 и 17 Закона РК «О персональных данных и их защите».','Дербес деректер: өңдеу негізі, барынша аз жинау, Қазақстанда сақтау және зерттеу үшін иесіздендіру — ҚР «Дербес деректер және оларды қорғау туралы» Заңының 7, 12 және 17-баптары.','Personal data: a lawful basis, minimisation, storage in Kazakhstan and de-identification for research — Articles 7, 12 and 17 of the Kazakhstan Law on Personal Data and Their Protection.'],
  lawHealth:['Медицинская тайна: сведения о пациенте и его обращениях защищены статьёй 273 Кодекса РК «О здоровье народа и системе здравоохранения».','Медициналық құпия: пациент және оның жүгінулері туралы мәліметтер ҚР «Халық денсаулығы және денсаулық сақтау жүйесі туралы» Кодексінің 273-бабымен қорғалады.','Medical confidentiality: patient information and care records are protected under Article 273 of the Kazakhstan Health Code.'],
  lawLink:['Открыть закон в «Әділет» ↗','Заңды «Әділет» жүйесінде ашу ↗','Read the law on Adilet ↗'],
  codeLink:['Открыть Кодекс в «Әділет» ↗','Кодексті «Әділет» жүйесінде ашу ↗','Read the Health Code on Adilet ↗'],
  beforeLive:['Перед подключением реальных данных','Нақты деректерді қоспас бұрын','Before connecting real data'],
  liveRule:['Нужно определить владельца и оператора, правовое основание, сроки хранения и права доступа; обеспечить хранение персональных данных в РК, защищённый серверный контур и проверку обезличивания. Публичный браузер должен получать только разрешённые агрегаты. Изменения интерфейса сами по себе не подтверждают полное юридическое соответствие.','Меншік иесі мен операторды, құқықтық негізді, сақтау мерзімдерін және қолжетімділік құқықтарын анықтау; дербес деректерді ҚР аумағында сақтау, қорғалған серверлік орта және иесіздендіруді тексеру қажет. Ашық браузерге тек рұқсат етілген агрегаттар берілуі тиіс. Интерфейс өзгерістері толық құқықтық сәйкестікті өздігінен растамайды.','The owner and operator, lawful basis, retention and access rights must be defined. Personal data require storage in Kazakhstan, a protected server environment and de-identification review. Public browsers must receive approved aggregates only. UI changes alone do not establish full legal compliance.'],
  storage:['В браузере сохраняется только выбранный язык. В региональном профиле географическая подложка загружается с OpenStreetMap; сервис получает обычные технические данные веб-запроса, включая IP-адрес. Рекламные трекеры не используются.','Браузерде тек таңдалған тіл сақталады. Өңірлік профильде географиялық негіз OpenStreetMap қызметінен жүктеледі; сервис веб-сұраудың қалыпты техникалық деректерін, соның ішінде IP-мекенжайды алады. Жарнамалық трекерлер қолданылмайды.','Only the selected language is saved in this browser. Regional profiles load the geographic basemap from OpenStreetMap; the service receives ordinary web-request metadata, including the IP address. No advertising trackers are used.'],
  legalDate:['Правовые тексты проверены: 20.09.2026.','Құқықтық мәтіндер тексерілді: 20.09.2026.','Legal texts reviewed: September 20, 2026.'],
  notClinical:['Не официальная статистика. Не предназначено для выбора лечения.','Ресми статистика емес. Ем таңдауға арналмаған.','Not official statistics. Not for treatment decisions.'],
  close:['Закрыть','Жабу','Close'],
  atlasFooter:['AMR Atlas · исследовательский прототип','AMR Atlas · зерттеу прототипі','AMR Atlas · research prototype'],
  legacy:['Лабораторная концепция','Зертханалық тұжырымдама','Clinical concept'],
  mapError:['Карту не удалось загрузить. Статистика и выбор региона доступны.','Карта жүктелмеді. Статистика және өңір таңдау қолжетімді.','The map could not be loaded. Statistics and region selection remain available.'],
  retry:['Повторить','Қайталау','Retry'],
  mapLoading:['Загрузка контуров…','Шекаралар жүктелуде…','Loading boundaries…'],
  focusRegion:['Открыть регион','Өңірді ашу','Open territory'],
  csvReady:['CSV с демонстрационными агрегатами подготовлен.','Демонстрациялық агрегаттары бар CSV дайын.','CSV of demonstration aggregates is ready.'],
  zoomIn:['Приблизить','Үлкейту','Zoom in'],
  zoomOut:['Отдалить','Кішірейту','Zoom out'],
  resetZoom:['Вся территория','Бүкіл аумақ','Fit territory'],
  zoomHint:['Перемещайте увеличенную карту мышью или пальцем','Үлкейтілген картаны тінтуірмен немесе саусақпен жылжытыңыз','Drag with a mouse or finger to pan a zoomed map'],
  showNumbers:['Показатели','Көрсеткіштер','Values'],
  showNames:['Названия','Атаулар','Names'],
  location:['Положение в Казахстане','Қазақстандағы орналасуы','Location in Kazakhstan'],
  skip:['Перейти к содержимому','Мазмұнға өту','Skip to content'],
  tableCaption:['Демонстрационные агрегаты, не клинические наблюдения','Клиникалық бақылаулар емес, демонстрациялық агрегаттар','Demonstration aggregates, not clinical observations'],
};
export const text = (key,lang='ru') => strings[key]?.[lang==='kk'?1:lang==='en'?2:0] ?? key;
