(()=>{
const API='https://ghoapi.azureedge.net/api';
const GEO='https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson';
const SNAPSHOT='./data/who-glass.json?v=20260921';
const CACHE_KEY='atlas-who-glass-live-v2';
const WEEK=7*24*60*60*1000;
const state={data:null,indicator:'mrsa',year:null,country:'KAZ',geo:null,search:''};
const $=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const fmtDate=v=>v?new Date(v).toLocaleString('ru-RU',{dateStyle:'medium',timeStyle:'short'}):'—';
const fmt=v=>Number(v).toLocaleString('ru-RU',{maximumFractionDigits:1});
function timeoutFetch(url,ms=20000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);return fetch(url,{signal:c.signal,cache:'no-store'}).finally(()=>clearTimeout(t));}
async function json(url){const r=await timeoutFetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}: ${url}`);return r.json();}
async function allPages(url){const out=[];let next=url;let guard=0;while(next&&guard<50){const body=await json(next);if(!Array.isArray(body.value))throw new Error('WHO API: отсутствует массив value');out.push(...body.value);next=body['@odata.nextLink']||body['odata.nextLink']||null;guard++;}return out;}
function normalizeName(s){return String(s||'').toLowerCase().replace(/–|—/g,'-').replace(/\s+/g,' ');}
function pickIndicators(rows){const english=rows.filter(r=>!r.Language||r.Language==='EN');const mrsa=english.find(r=>{const n=normalizeName(r.IndicatorName);return n.includes('methicillin-resistant')&&n.includes('staphylococcus aureus');});const ecoli=english.find(r=>{const n=normalizeName(r.IndicatorName);return n.includes('escherichia coli')&&n.includes('third-generation cephalospor');});if(!mrsa||!ecoli)throw new Error('WHO API: не найдены оба индикатора SDG 3.d.2');return{mrsa,ecoli};}
function recordValue(r){const x=Number(r.NumericValue);if(Number.isFinite(x))return x;const m=String(r.Value||'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):NaN;}
function recordYear(r){const y=Number(r.TimeDim);if(Number.isInteger(y))return y;const m=String(r.TimeDimensionBegin||r.Date||'').match(/(20\d{2}|19\d{2})/);return m?Number(m[1]):NaN;}
function optionalNumber(value){if(value===null||value===undefined||value==='')return null;const n=Number(value);return Number.isFinite(n)?n:null;}
async function fetchWhoDataset(){
  const [catalog,countryRows]=await Promise.all([allPages(`${API}/Indicator`),allPages(`${API}/DIMENSION/COUNTRY/DimensionValues`)]);
  const found=pickIndicators(catalog);
  const countryMap=new Map(countryRows.map(c=>[c.Code,{name:c.Title||c.Code,region:c.ParentTitle||''}]));
  const defs=[['mrsa',found.mrsa],['ecoli3gc',found.ecoli]];
  const blocks=await Promise.all(defs.map(async([key,ind])=>[key,ind,await allPages(`${API}/${encodeURIComponent(ind.IndicatorCode)}`)]));
  const seen=new Map();
  for(const [key,ind,rows] of blocks){for(const r of rows){if(r.Dim1!=null||r.Dim2!=null||r.Dim3!=null)continue;const code=r.SpatialDim,meta=countryMap.get(code);if(!meta)continue;const value=recordValue(r),year=recordYear(r);if(!Number.isFinite(value)||value<0||value>100||!Number.isInteger(year)||year<2015||year>2100)continue;const k=`${key}|${code}|${year}`;seen.set(k,{indicator:key,indicatorCode:ind.IndicatorCode,countryCode:code,country:meta.name,whoRegion:meta.region,year,value:+value.toFixed(4),low:optionalNumber(r.Low),high:optionalNumber(r.High)});}}
  const records=[...seen.values()].sort((a,b)=>a.indicator.localeCompare(b.indicator)||a.country.localeCompare(b.country)||a.year-b.year);
  const countries=new Set(records.map(r=>r.countryCode)),years=records.map(r=>r.year);
  if(records.length<500||countries.size<50)throw new Error(`WHO API: подозрительно малый набор (${records.length} записей, ${countries.size} стран)`);
  const maxYear=Math.max(...years),minYear=Math.min(...years),now=new Date().toISOString();
  return{meta:{source:'WHO Global Health Observatory / GLASS',checkedAt:now,generatedAt:now,version:`live-${maxYear}-${records.length}`,period:{from:minYear,to:maxYear},recordCount:records.length,countryCount:countries.size,refreshEveryDays:7,indicators:{mrsa:{code:found.mrsa.IndicatorCode,name:found.mrsa.IndicatorName},ecoli3gc:{code:found.ecoli.IndicatorCode,name:found.ecoli.IndicatorName}},sourceUrls:{glass:'https://www.who.int/data/gho/data/themes/topics/topic-details/GHO/global-antimicrobial-resistance-surveillance-system-glass',api:'https://ghoapi.azureedge.net/api'}},records};
}
function validDataset(d){return d&&d.meta&&Array.isArray(d.records);}
function saveCache(d){try{localStorage.setItem(CACHE_KEY,JSON.stringify(d));}catch{}}
function loadCache(){try{const d=JSON.parse(localStorage.getItem(CACHE_KEY)||'null');return validDataset(d)?d:null;}catch{return null;}}
function valueFor(code,year=state.year,indicator=state.indicator){return state.data.records.find(r=>r.countryCode===code&&r.year===Number(year)&&r.indicator===indicator)||null;}
function availableYears(){return [...new Set(state.data.records.filter(r=>r.indicator===state.indicator).map(r=>r.year))].sort((a,b)=>b-a);}
function countriesForYear(){const map=new Map();for(const r of state.data.records){if(r.indicator===state.indicator&&r.year===Number(state.year))map.set(r.countryCode,r);}return [...map.values()].sort((a,b)=>a.country.localeCompare(b.country,'ru'));}
function color(v){if(v==null)return'#516c78';if(v<10)return'#79d9ba';if(v<25)return'#39b9b0';if(v<50)return'#419bc0';return'#d7b678';}
function renderMeta(mode='snapshot',message=''){const m=state.data?.meta||{};const status=mode==='live'?'Данные проверены сейчас':mode==='cached'?'Локальный кэш':'Проверенный snapshot';$('dataset-meta').innerHTML=`<div class="meta-row"><span>Статус</span><b><span class="status-pill">${safe(status)}</span></b></div><div class="meta-row"><span>Версия набора</span><b>${safe(m.version||'—')}</b></div><div class="meta-row"><span>Период данных</span><b>${safe(m.period?`${m.period.from}–${m.period.to}`:'—')}</b></div><div class="meta-row"><span>Последняя проверка WHO</span><b>${safe(fmtDate(m.checkedAt))}</b></div><div class="meta-row"><span>Объём</span><b>${safe(m.recordCount??state.data?.records?.length??0)} записей · ${safe(m.countryCount??new Set((state.data?.records||[]).map(r=>r.countryCode)).size)} стран</b></div>${message?`<div class="callout warning">${safe(message)}</div>`:''}`;}
function renderControls(){const years=availableYears();if(!years.length)return;const previous=Number(state.year);state.year=years.includes(previous)?previous:years[0];$('year').innerHTML=years.map(y=>`<option value="${y}" ${y===Number(state.year)?'selected':''}>${y}</option>`).join('');}
function geoCode(f){const p=f.properties||{};return p['ISO3166-1-Alpha-3']||p.ISO_A3||p.iso_a3||p.ADM0_A3||p.ISO3||'';}
function project(pt){return[(Number(pt[0])+180)/360*1000,(90-Number(pt[1]))/180*500];}
function ringPath(ring){let d='',prev=null;for(const pt of ring){const [x,y]=project(pt);if(prev&&Math.abs(Number(pt[0])-prev)>180)d+=` M${x.toFixed(1)},${y.toFixed(1)}`;else d+=`${d?' L':'M'}${x.toFixed(1)},${y.toFixed(1)}`;prev=Number(pt[0]);}return d+' Z';}
function geometryPath(g){if(!g)return'';if(g.type==='Polygon')return g.coordinates.map(ringPath).join(' ');if(g.type==='MultiPolygon')return g.coordinates.flatMap(p=>p.map(ringPath)).join(' ');return'';}
function renderMap(){const box=$('world-map');if(!state.geo){box.innerHTML='<div class="map-empty">Геометрия карты мира недоступна. Список стран справа остаётся рабочим.</div>';return;}const paths=state.geo.features.map(f=>{const code=geoCode(f);if(!code)return'';const r=valueFor(code);const selected=code===state.country,kz=code==='KAZ';return`<path tabindex="0" role="button" class="world-country${selected?' selected':''}${kz?' kazakhstan':''}" data-country="${safe(code)}" d="${geometryPath(f.geometry)}" fill="${color(r?.value)}"><title>${safe((f.properties||{}).name||code)} · ${r?`${fmt(r.value)}%`:'нет данных'}</title></path>`;}).join('');box.innerHTML=`<svg viewBox="0 0 1000 500" preserveAspectRatio="xMidYMid meet" aria-label="Мировая карта WHO GLASS"><rect width="1000" height="500" fill="#0d2933"/>${paths}</svg>`;box.querySelectorAll('[data-country]').forEach(el=>{const pick=()=>{state.country=el.dataset.country;renderMap();renderCountry();renderList();};el.addEventListener('click',pick);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick();}});});}
function series(code){return state.data.records.filter(r=>r.indicator===state.indicator&&r.countryCode===code).sort((a,b)=>a.year-b.year);}
function renderCountry(){const panel=$('country-panel'),rows=series(state.country),current=valueFor(state.country);let name=rows[0]?.country||state.country;if(state.country==='KAZ')name='Казахстан';if(!current){panel.innerHTML=`<div class="eyebrow">${safe(name)}</div><h2>Нет опубликованного значения за ${safe(state.year)}</h2><p class="muted">В публичном WHO GHO-фиде выбранного индикатора значение для этой страны и года отсутствует. Это не означает отсутствие AMR.</p>${state.country==='KAZ'?'<div class="callout"><strong>Казахстан — основной контур AMR Atlas.</strong> Для региональных данных используйте национальную карту, а WHO GLASS здесь служит внешним глобальным контекстом.</div><a class="button" href="./index.html">Открыть Казахстан</a>':''}<div class="country-list" id="country-list"></div>`;renderList();return;}const bars=rows.map(r=>`<div class="trend-column"><div class="trend-bar" style="height:${Math.max(3,r.value)}%" title="${safe(r.year)}: ${safe(fmt(r.value))}%"></div><span>${r.year}</span></div>`).join('');panel.innerHTML=`<div class="eyebrow">${safe(current.whoRegion||'WHO GLASS')}</div><h2>${safe(current.country)}</h2><div class="country-value">${fmt(current.value)}<small>% R</small></div><p class="muted">${state.indicator==='mrsa'?'MRSA среди S. aureus инфекций кровотока':'E. coli, устойчивая к цефалоспоринам III поколения, среди инфекций кровотока'} · ${safe(current.year)}</p>${current.low!=null&&current.high!=null?`<div class="callout">WHO interval: ${fmt(current.low)}–${fmt(current.high)}%</div>`:'<div class="callout">Публичный индикаторный фид не гарантирует наличие размера выборки и доверительного интервала для каждой записи. AMR Atlas не вычисляет их без знаменателя.</div>'}<h3>Динамика</h3><div class="trend">${bars}</div><div class="country-list" id="country-list"></div>`;renderList();}
function renderList(){const list=$('country-list');if(!list)return;const q=state.search.toLowerCase();const rows=countriesForYear().filter(r=>!q||r.country.toLowerCase().includes(q)||r.countryCode.toLowerCase().includes(q));list.innerHTML=rows.map(r=>`<button type="button" data-pick="${safe(r.countryCode)}" class="${r.countryCode===state.country?'active':''}"><span>${safe(r.country)}</span><small>${fmt(r.value)}%</small></button>`).join('');list.querySelectorAll('[data-pick]').forEach(b=>b.addEventListener('click',()=>{state.country=b.dataset.pick;renderMap();renderCountry();}));}
async function loadGeo(){try{state.geo=await json(GEO);}catch(e){console.warn(e);state.geo=null;}renderMap();}
async function refreshLive(force=false){const btn=$('refresh-who');btn.disabled=true;btn.textContent='Проверка WHO…';try{if(!force){const c=loadCache();if(c&&Date.now()-Date.parse(c.meta.checkedAt)<WEEK){state.data=c;renderMeta('cached');renderAll();return;}}const d=await fetchWhoDataset();state.data=d;saveCache(d);renderMeta('live');renderAll();}catch(e){console.error(e);renderMeta('snapshot',`Проверка WHO не удалась: ${e.message}. Используется последний доступный набор.`);}finally{btn.disabled=false;btn.textContent='Проверить WHO сейчас';}}
function renderAll(){renderControls();renderMap();renderCountry();renderList();}
$('indicator').addEventListener('change',e=>{state.indicator=e.target.value;state.year=null;renderAll();});$('year').addEventListener('change',e=>{state.year=Number(e.target.value);renderMap();renderCountry();renderList();});$('country-search').addEventListener('input',e=>{state.search=e.target.value;renderList();});$('refresh-who').addEventListener('click',()=>refreshLive(true));
(async()=>{try{const snapshot=await json(SNAPSHOT);if(!validDataset(snapshot))throw new Error('Некорректный snapshot');state.data=snapshot;renderMeta('snapshot');renderAll();}catch(e){state.data={meta:{version:'bootstrap',checkedAt:null,period:null,recordCount:0,countryCount:0},records:[]};renderMeta('snapshot','Локальный snapshot пока пуст. Выполняется запрос к WHO.');}loadGeo();const checked=Date.parse(state.data.meta.checkedAt||0);if(!state.data.records.length||Date.now()-checked>WEEK)refreshLive(false);})();
})();
